### ISSUE TITLE
nvim-cmp compeletion menu highlight consistency

### ISSUE THREAD

**Issue by curtainp** [glepnir/flipped.nvim#3]
now `porcelain` don't set nvim-cmp compeletion menu highlight, which cause highlight Inconsistency,

before:
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/20302295/228713372-31d50026-548e-4161-9c52-baaaa7415178.png">

after:
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/20302295/228713630-76d215b5-9274-4c81-b278-b358647ef37b.png">

Possible fixes:
```
     --cmp
+    CmpPmenu = { fg = f.base05 },
+    CmpDoc = { bg = f.base05 },
+    CmpSel = { fg = f.base03 },
     CmpItemAbbr = { fg = f.manaohui },
     CmpItemAbbrMatch = { fg = f.green },
     CmpItemKind = { fg = f.blue },
```

**Comment by glepnir** [comment]
sry I don't use that plugin.
